name: react deploy to r2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install modules
        uses: ./.github/actions/cache-module

  build:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        uses: ./.github/actions/cache-build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Cached Build
        id: cached-build
        uses: actions/cache@v4
        with:
          path: '**/dist'
          key: ${{ runner.os }}-npm-build-${{ github.sha }}
      - name: Deploy to R2
        uses:  cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: r2 object put frontend/index.html --file=dist/index.html

